name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello, ${{ github.event.inputs.name }}!"
