name: Manual Trigger Example

on:
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello, ${{ github.event.inputs.name }}!"
