name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select a branch'
        required: true
        default: 'main'
        type: choice
        options:
          - 'main'
          - 'dev'
          - 'staging'


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello, ${{ github.event.inputs.name }}!"
