name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      branch:
      description: 'Run wokflow on'
      default: 'stage'
      type: choice
      options:
        - 'stage'


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello, ${{ github.event.inputs.name }}!"
