name: Merge Main to Stage

permissions:
  contents: write 
  
on:
  workflow_dispatch:

jobs:
  merge_to_stage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Git User
      run: |
        git config --global user.name "codeBKashif"
        git config --global user.email "temujin398@gmail.com"

    - name: Merge Main into Stage
      run: |
        git fetch origin stage
        git checkout stage
        git merge origin/main --no-ff --allow-unrelated-histories 
        git pull origin stage
        git add -A
        git commit -m "Merged main into stage"
        git push origin stage
